---
title: "Medication Waste"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---
```{r setup, include=TRUE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(datasets)
library(gghighlight)
library(shiny)
library(shinydashboard)
library(DT)
library(shinyWidgets)
library(readxl)
library(plotly)

projectdata<-read_excel('MedicationWasteReduction.xlsx', sheet = "Orders", .name_repair = "universal")
projectdrugs<-read_excel('MedicationWasteReduction.xlsx', sheet = "Drugs-Prices", .name_repair = "universal")

projectdrugs$Drug.name[projectdrugs$Drug.name== "VANCOMYCIN IVPB (1000-1500MG)   *SH*"] <- "1. VANCOMYCIN IVPB (1000-1500MG)"
projectdrugs$Drug.name[projectdrugs$Drug.name== "PANTOPRAZOLE INFUSION   *SH*"] <- "2. PANTOPRAZOLE INFUSION   *SH*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "FUROSEMIDE INFUSION *S*"] <- "3.FUROSEMIDE INFUSION *S*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "LEVETIRACETAM IVPB   *SH*"] <- "4.LEVETIRACETAM IVPB   *SH*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "NOREPINEPHRINE INFUSION *SH*"] <- "5.NOREPINEPHRINE INFUSION *SH*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "VASOPRESSIN INFUSION   *SH*"] <- "6.VASOPRESSIN INFUSION   *SH*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "LEVOTHYROXINE SODIUM 100 MCG IV SOLR *SH*"] <- "7.LEVOTHYROXINE SODIUM 100 MCG IV SOLR *SH*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "CITRATE TRI SODIUM 0_5% 3191 ML *S*"] <- "8.CITRATE TRI SODIUM 0_5% 3191 ML *S*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "PRISMASATE B22GK 4/0 *S*"] <- "9.PRISMASATE B22GK 4/0 *S*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "SODIUM BICARBONATE +/- KCL CVVH OOSQ *S*"] <- "10.SODIUM BICARBONATE +/- KCL CVVH OOSQ *S*"
projectdrugs$Drug.name[projectdrugs$Drug.name== "NS +/-CALCIUM +/- POTASSIUM (CVVH NON-CITRATE) *S*"] <- "11.NS +/-CALCIUM +/- POTASSIUM (CVVH NON-CITRATE) *S*"

projectdata<-merge(projectdata, projectdrugs)

projectdata<-projectdata %>% 
  mutate(hour=hour(Cancel.Date.time),
         doses=ceiling(as.double((Cancel.Date.time-Start.Date.time)/60)/Duration..Time.between.doses..in.hours..),
       money=doses*price.per.dose)

hosdata<-projectdata
total<-hosdata %>% summarize(count=n())

byhour<-hosdata %>% 
        group_by(hour) %>% 
        summarize(num=n(),
                  costH=sum(money),
                  probC=num/as.double(total)
                  )
byhour$prod<-as.double(c(0,0,0,0,0,0,3,6,9,12,15,18,21,24,0,0,0,0,0,0,0,0,0,0,0))

byhour<-byhour %>% mutate(inv=abs(((hour+34)%%24)-24),
                          hos=prod+inv,
                          waste=hos*probC*costH,
                          wasteJIT=prod*probC*costH)

CurrentModel <-byhour %>% summarize(total=sum(waste, na.rm=TRUE))
JITmodel <- byhour %>% summarize(total=sum(wasteJIT, na.rm=TRUE))
 
Savings<-CurrentModel-JITmodel


data2<-projectdata
data2$Drug.name <- 'Overall'

projectdata<-rbind(projectdata, data2)

by_drug<-group_by(projectdata, Drug.name)

drugch<-summarize(by_drug,
                  count = n())

rm<- lm(money ~ hour + Drug.name, data=hosdata)

```
Descriptive Analytics
=====================================
Column {.sidebar}
-----------------------------------------------------------------------

### Select The Drug

```{r}
ch_choice = c(drugch$Drug.name)
selectInput("drug", "Drug", choices = ch_choice)

```
## Row 1
-----------------------------------------------------------------------


### 
    
```{r}

renderValueBox(
  {total<-projectdata %>% 
    filter(Drug.name == input$drug) %>% 
    summarize(as.integer(sum(money, na.rm=TRUE)))
    valueBox(value = paste("$", total, sep = ""),
           subtitle = "Cost of wastage",
           icon = icon("sack-dollar"),
           color = "red",
           )})

```

### 
    
```{r}
renderValueBox(
  {total<-projectdata %>% 
  filter(Drug.name == input$drug) %>% 
  summarize(as.integer(sum(doses, na.rm=TRUE)))
  valueBox(value = total,
  subtitle = "Doses wasted",
  icon = icon("hashtag"),
  color= "red",
  href=NULL)
  })

```

## Row 2
-----------------------------------------------------------------------

### Cancellation per hour

```{r}

drug_inp <- reactive({input$drug})

renderPlot(
  projectdata %>% 
  filter(Drug.name == input$drug) %>% 
  group_by(hour) %>% 
  ggplot(mapping = aes(x = hour)) +
  geom_bar(color = "brown2", fill = "brown2", stat= "count")+
  stat_count(geom = "text", colour = "black", size = 3.5, aes(label = ..count..),position=position_stack(vjust=0.9))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  labs(x="Hour", y="Doses Wasted")
)

```
## Row 3
-----------------------------------------------------------------------

### Wastage per Hour

```{r}

drug_inp <- reactive({input$drug})

renderPlot(
  projectdata %>% 
  filter(Drug.name == input$drug) %>% 
  group_by(hour) %>% 
  summarise(total_cost = round(sum(money))) %>%
  ggplot(mapping = aes(x = hour, y = total_cost)) +
    geom_bar(color = "chartreuse3", fill = "chartreuse3", stat = "identity") +
    geom_text(aes(label = paste("$", ..y.. , sep = "")),position=position_stack(vjust=0.9))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  labs(x="Hour", y="Money Wasted")
)

```
Regression Model
=====================================
Column {.sidebar}
-----------------------------------------------------------------------

### Select The Drug

```{r}
cha_choice = c(drugch$Drug.name)
cha_choice<-cha_choice[-12]
selectInput("druga", "Druga", choices = cha_choice)

```
### Select The Hour

```{r}
chi_choice = c(byhour$hour)
chi_choice<-chi_choice[-25]
selectInput("hour", "Hour", choices = chi_choice)

```
## Row 1
-----------------------------------------------------------------------

### 
    
```{r}

renderValueBox(
  { nd<-data.frame(hour=as.numeric(input$hour), Drug.name=input$druga)
    theory<-predict(rm, newdata=nd, interval="confidence", level=0.95)
    valueBox(value = paste("$", round(theory[1]), sep = ""),
           subtitle = "Cost of wastage",
           icon = icon("sack-dollar"),
           color = "blue",
           )})

```
## Row 2
-----------------------------------------------------------------------

### 
    
```{r}

renderValueBox(
  { nd<-data.frame(hour=as.numeric(input$hour), Drug.name=input$druga)
    theory<-predict(rm, newdata=nd, interval="confidence", level=0.95)
    valueBox(value = paste("$", round(theory[2]), sep = ""),
           subtitle = "Cost of wastage: Lower Estimate",
           icon = icon("sack-dollar"),
           color = "green",
           )})

```
## Row 3
-----------------------------------------------------------------------

### 
    
```{r}

renderValueBox(
  { nd<-data.frame(hour=as.numeric(input$hour), Drug.name=input$druga)
    theory<-predict(rm, newdata=nd, interval="confidence", level=0.95)
    valueBox(value = paste("$", round(theory[3]), sep = ""),
           subtitle = "Cost of wastage: Higher Estimate",
           icon = icon("sack-dollar"),
           color = "red",
           )})

```

Hours of Supply
=====================================

## Row 1
-----------------------------------------------------------------------
### 
    
```{r}

renderValueBox(
  {valueBox(value = paste("$", as.integer(Savings), sep = ""),
           subtitle = "Savings",
           icon = icon("sack-dollar"),
           color = "aqua",
           )})

```
## Row 2
-----------------------------------------------------------------------
```{r}
renderPlotly(tibble(rbind(tibble('Hour' = byhour$hour, 'Waste' = round(byhour$wasteJIT), 'System' = 'JIT'),
                        tibble('Hour' = byhour$hour, 'Waste' = round(byhour$waste), 'System' = 'Old')
                        ))%>%
  ggplot(mapping = aes(x=Hour, y = Waste, fill= System)) +
  geom_bar(position="dodge", stat="identity")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))
)
```   


